theme: jekyll-theme-merlot
title: CSS3 Experiments
description: Learning by doing
show_downloads: false
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
